### ISSUE TITLE
iOS: posted images in DM disappear locally but are received by counterparty

### ISSUE THREAD

**Issue by jalehman** [holium/realm-support#36]
Realm desk hash: `0ve.uafpm.neaq3.d9vom.7ak4t.flr7h.l5nc3.893u3.5feig.rgaqi.ovfqu`

Here's what happens:
1. I send a message with a photo from my camera roll to a DM
2. The message shows up as sent in the DM
3. I navigate out of the thread
4. I navigate back, and the image message is gone
5. The counterparty indicates receipt of the image

**Comment by e1block** [comment]
I was able to repro this once on build 78, but not consistently:

* Toggle airplane mode on device
* Send image
* Return to chat list then back to DM
* Image is gone
* Return to chat list, pull to refresh (scry), image is there

Currently, were not writing image uploads to local store before hand, and were not using the sync thread poke for that case either. Thus, even though the SSE channel reconnected (assuming), the event got dropped/missed somehow. Writing to local + thread poke should fix this (what we do for text messages).

How that event gets dropped is not clear however, since Urbit is supposed to wait for an ACK.

**Comment by e1block** [comment]
We have a fix for this coming in build 79.

**Comment by e1block** [comment]
Its out.

**Comment by jalehman** [comment]
This appears to have resolved the issue. Thanks!
